import React from "react";
import { Property } from "../components";
/**
 * This is a React functional component that renders a container for featured properties with a title
 * and a list of featured items.
 * @returns A React component that renders a container for featured properties, with a header and a
 * list of featured items. The list of featured items is generated by mapping over an array of
 * properties passed as a prop called "featured".
 */

const PropertyRelatedContainer = ({ featured }) => {
  return (
    <Property.Featured>
      <Property.FeaturedHeader>
        <Property.Title>Featured Properties</Property.Title>
      </Property.FeaturedHeader>
      <Property.FeaturedContent>
        {featured.map((property) => (
          <FeaturedItem key={property.id} property={property} />
        ))}
      </Property.FeaturedContent>
    </Property.Featured>
  );
};

const FeaturedItem = ({ property }) => {
  return (
    <Property.FeaturedItem>
      <Property.ItemLeft>
        <Property.Image source={property.images[1]} />
      </Property.ItemLeft>
      <Property.ItemRight>
        <Property.Subtitle>
          <Property.Anchor to={`/property/${property.id}`}>
            {property.title}
          </Property.Anchor>
        </Property.Subtitle>
        <Property.Text>
          <Property.Icon name="fas fa-map-marker-alt"></Property.Icon>{" "}
          {property.address.address}
        </Property.Text>
        <Property.FeaturedInfo>
          <Property.Text>
            {property.type === "rental" ? "Rent" : "Sale"}
          </Property.Text>
          <Property.Text>$ {property.price}</Property.Text>
        </Property.FeaturedInfo>
      </Property.ItemRight>
    </Property.FeaturedItem>
  );
};

export default PropertyRelatedContainer;
